### ISSUE TITLE
Make a release without camlp4

### ISSUE THREAD

**Issue by XVilka** [jserot/lascar#1]
Camlp4 release for OCaml 4.08 is the last release ever - see the [official announcement](https://discuss.ocaml.org/t/the-end-of-camlp4/4216). Since the project already dropped camlp4 dependency it would be good to make the release for opam as well: http://opam.ocaml.org/packages/lascar

**Comment by jserot** [comment]
Next release (0.6) is planned in the next few days. It will be camlp4-less.

**Comment by jserot** [comment]
v0.6-alpha is out. It is camlp4-less.
